### ISSUE TITLE
作ったデッキのページを開くと500エラー吐く

### ISSUE THREAD

**Issue by TBSten** [Mishima-Ryuji/ZutomayoCard#19]
## 不具合の内容

- 作ったデッキのページを開くとエラー吐きます
- 「自分の」欄から開くとこうなります 

## 参考文献

https://discord.com/channels/1024874885392121988/1118563954319446026/1136865845818167417

**Comment by Mishima-Ryuji** [comment]
原因はFirebaseのrulesの権限エラー。当該エラーが発生したデッキは、非公開かつおすすめされていないデッキであった。手元の環境では、おすすめされていない非公開のデッキを作成者でログインしたらアクセスすることができた。再現性がなかったので、発生条件と認識のずれがないかを現在確認中。

https://discord.com/channels/1024874885392121988/1118563954319446026/1137423176276643920

**Comment by TBSten** [comment]
getStaticProps(というかサーバ側)でユーザ情報が取れてないのが原因っぽいです。

![](https://media.discordapp.net/attachments/1118563954319446026/1137954814978969712/2023-08-07_12.34.12.png?width=1410&height=388)

![](https://media.discordapp.net/attachments/1118563954319446026/1137954815209635970/2023-08-07_12.34.01.png?width=1410&height=176)

となるとSSR+FirebaseAdminSDKを使って([このドキュメント](https://media.discordapp.net/attachments/1118563954319446026/1137954815209635970/2023-08-07_12.34.01.png?width=1410&height=176)あたりが参考になりそう）サーバ側でユーザを特定できるように調整する必要が出てきそうです。

が、一旦はSGせずにクライアント側でロードする形で対応するのが速そうです。
