### ISSUE TITLE
説明等の中でカード名だけだと分かりにくいので当該カードにリンクを貼れる機能

### ISSUE THREAD

**Issue by Mishima-Ryuji** [Mishima-Ryuji/ZutomayoCard#22]
## 機能の説明

https://discord.com/channels/1024874885392121988/1118563700031356938/1136883776413241344

## 実装内容

 

- [ ]

## 参考文献

-

**Comment by Mishima-Ryuji** [comment]
@TBSten がリッチエディタを導入しているとのことらしい。

**Comment by TBSten** [comment]
issueもう切ってありますよー
#20 

(issue名がわかりにくくて申し訳ない...)
